# -*- coding: utf-8 -*-
"""data(web) crawling (working) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBy2SY9hGGrP5QM5xvXsDSYtMxnflKnv
"""

import urllib.request
from bs4 import BeautifulSoup

#scraping web link
address= 'https://www.rottentomatoes.com/m/incredibles_2/reviews/'

page = urllib.request.urlopen(address)
soup = BeautifulSoup(page,'html.parser')
#print full html page of address
print (soup.prettify())



#find_all():- python er function jar kaj holo sob kichu tule niye asa

#review = soup.find_all('kotha theke niye asbo(div)',say attribute(attrs=){'kothai ase(class)': 'tar name(the_review)'})
review = soup.find_all('div',attrs={'class':'the_review'})
print (review)

for i in review:
    print("review :")
    #get_text: only for text
    #print(i.get_text())
    print(i.get_text(),"\n")



