# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VCO7oydtJRxFl6f_u4hS6tkBwKolQw2t
"""

import requests
import bs4

from bs4 import BeautifulSoup

res = requests.get('https://www.prothomalo.com')

res.text

soup = bs4.BeautifulSoup(res.text,'lxml')

title = soup.select('title')
title

title[0]

title[0].getText()

